openshift/cluster-storage-operator

Dockerfile
Please do not merge without green `e2e-aws` like here https://github.com/openshift/cluster-storage-operator/pull/2
An example is above where the crashlooping pod for this operator is preventing merges on other repos here:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/225/pull-ci-openshift-machine-config-operator-master-e2e-aws/618
```console
failed: (5m2s) 2018-12-09T20:36:19 "[Feature:Platform][Smoke] Managed cluster should start all core operators [Suite:openshift/conformance/parallel] [Suite:openshift/smoke-4]"
```
because
```console
sh-4.2$ oc -n openshift-cluster-storage-operator get all
NAME                                           READY     STATUS             RESTARTS   AGE
pod/cluster-storage-operator-6dd8c5774-v5std …
```
=> Dockerfile: remove operator from release payload

Makefile
GOPATH does not have to be a single path. Downstream, it isn't.
=> Update Makefile to use FIRST_GOPATH

pkg/controller/clusterstorage/clusterstorage_controller.go
Unsupported platform isn't really a fatal error. We are just not going to install a storageclass. This fixes deployment on libvirt.
=> Handle unsupported platform errors gracefully

manifests/02-deployment.yaml, manifests/03-cluster-operator.yaml, pkg/controller/clusterstorage/clusterstorage_controller.go
The new contract with operators is that we report the version when
we reach "level" (have rolled out the version we got handed in the
payload) and are available, which ensures that the CVO can wait
until it sees us completely roll out the payload. This makes upgrade
status much clearer.
See https://github.com/openshift/cluster-image-registry-operator/pull/219 for more context, we are rolling this out across all operators.
=> version: Set the cluster operator version based on the payload

pkg/controller/clusterstorage/clusterstorage_controller.go
I think even though ClusterOperator is being created correctly, we need to stop the operation from requeing.  It should fix - https://github.com/openshift/cluster-storage-operator/issues/19
cc @wongma7 @bertinatto
=> Do not re-queue if error is unsupported

manifests/00-namespace.yaml
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
=> Add node-selector annotation to namespace

manifests/02-deployment.yaml
In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …
=> Fix tolerations

pkg/controller/clusterstorage/clusterstorage_controller.go
Reverts openshift/cluster-storage-operator#38
The labels were set by hand by an engineer who should not have been setting them. Reverting.
=> Revert "[release-4.1] Bug 1717640: Add related objects to Status"

pkg/controller/clusterstorage/clusterstorage_controller.go
It seems we already set the `Reason` if we encounter an error; however, we don't populate this field with values for expected configurations. I've added in a string to indicate that the starting statuses are expected.
This is for [BZ-1741071](https://bugzilla.redhat.com/show_bug.cgi?id=1741071).
=> Included default reason strings.

pkg/controller/clusterstorage/clusterstorage_controller.go, pkg/controller/clusterstorage/clusterstorage_controller_test.go
Updates the ClusterStorageOperator to check for changes made to the default StorageClass assets. If changes are found in either AllowVolumeExpansion or MountOptions, update the default StorageClass to use the new values.
This change also prevents users from adjusting these attributes from the ones used in the assets. We should likely document that restriction, and advise users to create a new storage class if changes are needed.
=> Bug 1751641: Enables updating of StorageClass if a change is detected.

manifests/01-cluster-role.yaml, pkg/controller/clusterstorage/clusterstorage_controller.go, pkg/controller/clusterstorage/clusterstorage_controller_test.go, pkg/controller/validation/check_snapshot.go, pkg/controller/validation/check_snapshot_test.go
This includes a check for the VolumeSnapshot CRD. If we detect v1alpha1 of the CRD, then we mark the Operator as Available, but Upgradeable=false.
Note that this needs to be included in 4.3; however, I think it would be useful to have some of these validations (since we're going to be checking for CSI Drivers) in current versions as well.
=> Bug 1835869: Included check for v1alpha VolumeSnapshot CRD

pkg/controller/clusterstorage/clusterstorage_controller.go, pkg/controller/validation/check_snapshot.go, pkg/controller/validation/check_snapshot_test.go
Continues the work in BZ1835869 to check for VolumeSnapshotClass and VolumeSnapshotContent. This puts the CRDs into a map and runs through them, building up the final error message along the way.
=> Bug 1835869: Updates validation to check for VolumeSnapshotClass and VolumeSnapshotContent

manifests/01-cluster-role.yaml, pkg/controller/clusterstorage/clusterstorage_controller.go, pkg/controller/clusterstorage/clusterstorage_controller_test.go, pkg/controller/validation/check_snapshot.go, pkg/controller/validation/check_snapshot_test.go
This is a manual cherry-pick for the following PRs:
* https://github.com/openshift/cluster-storage-operator/pull/55
* https://github.com/openshift/cluster-storage-operator/pull/57
This includes a check for the VolumeSnapshot CRD. If we detect v1alpha1 of the CRD, then we mark the Operator as Available, but Upgradeable=false.
=> Bug 1846112: Includes validation check for VolumeSnapshot v1alpha1 CRDs

pkg/operator/defaultstorageclass/controller.go, pkg/operator/defaultstorageclass/controller_test.go
The operator should mark itself as `Available` when on a platform that does not have a default StorageClass (yet).
library-go status syncer expects at least Available condition in `storage` CR to mark the OperatorStatus as `Available`.
=> Fix installation on usupported platforms like oVirt

assets/csidriveroperators/manila/05_clusterrole.yaml, assets/csidriveroperators/manila/09_credentials.yaml, pkg/generated/bindata.go
As Manila CSI driver moves to openshift-manila-csi-driver, CSO must update
some code too:
- Manila operator must have permissions to create/update secrets in openshift-manila-csi-driver namespace to be able to translate OpenStack credentials to the format required by Manila.
- Manila operator will need to create CredentialsRequest for the driver (because now it's in a separate NS). Therefore CSO should use another name for the operator's CredentialsRequest, so the name implies it's for the operator only.
=> Move to openshift-manila-csi-driver namespace

manifests/04_deployment.yaml
Pass NFS driver image name to Manila operator.
Fixes this error in Manila CSI driver Deployment:
```
Failed to apply default image tag "${NFS_DRIVER_IMAGE}": couldn't parse
image reference "${NFS_DRIVER_IMAGE}": invalid reference format:
repository name must be lowercase
```
=> Fix NFS driver deployment

pkg/operator/starter.go
* Don't report AWS EBS namespace as related, it's used only by OLM-based operator in 4.5.
* Report Manila namespace as related, it will have this extra namespace forever.
=> Bug 1865797: Fix related namespaces

pkg/operator/csidriveroperator/csioperatorclient/aws.go, pkg/operator/csidriveroperator/csioperatorclient/manila.go, pkg/operator/csidriveroperator/csioperatorclient/types.go, pkg/operator/csidriveroperator/deploymentcontroller.go, pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/csidriveroperator/olmremovalcontroller.go, pkg/operatorclient/operatorclient.go
OLMOperatorRemovalController removes CSI driver operator from OLM. It must run before CSO starts CSI driver operator to make sure only one operator / only one driver runs at a time.
It removes Subscription, CSV, waits for the old operator Deployment to get removed by OLM and finally it force-removes the old CR (by clearing all its finalizers).
It signalizes that it's finished with OLM removal by setting `ManilaOLMOperatorRemovalAvailable: true`. This is then recognized by CSIDriverStarterController that runs the new operator.
=> Bug 1862523: Add migration controller

assets/csidriveroperators/aws-ebs/05_clusterrole.yaml, pkg/generated/bindata.go
Please note this is a temporary measure, I intend to remove these permissions and disable the support for volume-in-use error in resizer for EBS because it is not applicable.
However, without this fix - we have a chicken and egg problem. The rebase PR of external-resizer will not merge until external-resizer can list the pods.
=> Bug 1867704: Give pod listing permissions to aws operator

pkg/csoclients/csoclients.go, pkg/operator/csidriveroperator/csioperatorclient/manila.go
The sync failed, because CSO's KubeInformersForNamespaces did not watch openshift-config namespace.
Add the namespace to the namespace list + make sure that CSO panics on similar errors in future.
=> Bug 1867735: Fix syncing of Manila CA certificate

pkg/operator/defaultstorageclass/controller.go
There was an issue in [BZ1869516](https://bugzilla.redhat.com/show_bug.cgi?id=1869516) where the CSO paniced during an upgrade on a baremetal UPI cluster. When examining the Infrastructure resource, there was no PlatformStatus defined.
This should check and return an unsupportedPlatform if the PlatformStatus is nil.
=> Bug 1869516: Prevent crash if PlatformStatus is nil

assets/csidriveroperators/aws-ebs/05_clusterrole.yaml, assets/csidriveroperators/ovirt/05_clusterrole.yaml, pkg/generated/bindata.go
The external-attacher needs to patch volumeattachment/status. Add such permission to AWS EBS and oVirt operators, so they're able to grant it to the driver.
=> Bug 1871051: Add CSI operators permissions to patch volumeattachment/status

assets/csidriveroperators/aws-ebs/07_deployment.yaml, assets/csidriveroperators/manila/07_deployment.yaml, assets/csidriveroperators/ovirt/07_deployment.yaml, pkg/generated/bindata.go
Updates the CSI Driver deployment files to allow scheduling on master nodes.
=> Bug 1873175: Allow CSI Drivers to run on master nodes

manifests/03_credentials_request_openstack.yaml
```
$ oc get credentialsrequests.cloudcredential.openshift.io -A | grep csi
openshift-cloud-credential-operator   aws-ebs-csi-driver-operator           
openshift-cloud-credential-operator   ovirt-csi-driver-operator             
openshift-cloud-credential-operator   openshift-manila-csi-driver-operator  
```
Rename to `manila-csi-driver-operator`.
=> Bug 1868339: Rename Manila CredentialsRequest to a name similar to the other ones

pkg/operator/csidriveroperator/olmremovalcontroller.go
Don't add any messages to Available/Progressing conditions if the old Manila operator wasn't found by CSO.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1874738
=> Bug 1874738: Remove noisy messages in Available/Progressing conditions

cmd/manager/main.go
Leader-for-life leader election causes problems when downgrading **from** CSO 4.6, which uses library-go and doesn't set an `ownerReference` in the `ConfigMap` metadata.
This patch identifies if the lock was created by CSO 4.6 and, if so, deletes it so that CSO 4.5 can become the leader using the leader-for-life model.
More on the the problem:
On a downgrade from 4.5 to 4.6 scenario, the leader election `ConfigMap` is created by CSO 4.6 (library-go) and it doesn't have any `ownerReference` set.
However, CSO 4.5 uses `operator-sdk` with leader-for-life election approach, and it expects that the `ConfigMap` either doesn't exist or exists but has an `ownerReference` set (in order to know whether the lock belongs to it or not).
Since it doesn't find any, it tries to create one, but it gets …
=> Bug 1882394: Delete lock created by CSO 4.6

manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml, manifests/01_operator_namespace.yaml
cluster-storage-operator and cluster-csi-snapshot-controller-operator both run at runlevel 50 and in the same namespace. Create the namespace at runlevel 49, so the namespace is created only once and the authoritative version is in this repo.
The namespace creation will be removed from cluster-csi-snapshot-controller-operator in a subsequent PR.
=> Bug 1879365: Move CSO namespace to lower runlevel

Gopkg.toml, vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
In a 4.6 -> 4.5 downgrade scenario, CSO 4.5 could be started before CSO 4.6 is terminated.
This could happen:
1. CSO 4.6 creates a _leader_with_lease_ `ConfigMap`
2. User downgrades to OCP 4.5
3. CSO 4.5 starts and sees that the existing `ConfigMap` was created by CSO 4.6, so it deletes it and continues to initialize
4. CSO 4.6 sees that its _leader_with_lease_ `ConfigMap` was deleted and quickly re-created it
5. CSO 4.5 is still starting up. Now it tries to become the leader by creating the _leader_for_life_ `ConfigMap`, but that fails because another object with the same name exists
6. CSO 4.5 (i.e., operator-sdk) gets stuck in a loop trying to create the lock, but it fails forever
This patch introduces a check in the legacy operator-sdk code to prevent CSO 4.5 from getting stuck in the …
=> Bug 1882394: UPSTREAM: <carry>: operator-sdk: return error if lock is not leader-for-life

Dockerfile
Updating cluster-storage-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/cluster-storage-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating cluster-storage-operator builder & base images to be consistent with ART

assets/csidriveroperators/aws-ebs/01_namespace.yaml, assets/csidriveroperators/manila/01_namespace.yaml, assets/csidriveroperators/ovirt/01_namespace.yaml, manifests/02_csi_driver_operators_namespace.yaml, pkg/generated/bindata.go
=> Bug 1894025: Add annotations to cluster-csi-drivers namespace

assets/csidriveroperators/openstack-cinder/07_deployment.yaml, pkg/generated/bindata.go
The images were hardcoded to quay.io registries. They should instead be
templated to use values from the release payload.
Bindata generated with `make update-bindata`.
=> Bug 1902552: Fix cinder-csi images

assets/csidriveroperators/openstack-cinder/07_deployment.yaml, pkg/generated/bindata.go
This should fix the "Managed cluster should ensure control plane pods do
not run in best-effort QoS" CI test that is currently failing with:
5 pods found in best-effort QoS:
openshift-cluster-csi-drivers/openstack-cinder-csi-driver-controller-5bfc8fdf46-k9h6f is running in best-effort QoS
openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-gqmzg is running in best-effort QoS
openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-hn5pp is running in best-effort QoS
openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-nsffx is running in best-effort QoS
openshift-cluster-csi-drivers/openstack-cinder-csi-driver-operator-7f968db7f-hkvmj is running in best-effort QoS
https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-opens …
=> Bug 1902601: Fix resources in cinder csi deployment template

assets/csidriveroperators/aws-ebs/05_clusterrole.yaml, pkg/generated/bindata.go
To support custom CA bundles for AWS C2s, the AWS EBS opreator needs to sync the cloud config ConfigMap from the openshift-config-managed namespace into the operator's namespace.
https://issues.redhat.com/browse/CORS-1584
=> aws: grant ebs operator permission to read configmaps

manifests/03_credentials_request_vsphere.yaml, manifests/09_deployment.yaml, manifests/image-references
Deploy vsphere problem detector as a sidecar.
About metrics - I am wondering if same operator can have two endpoints that can be scraped by prometheus. Looking into existing operators that use `ServiceMonitor` , I don't find any example of this happening.
=> Add YAMLs for starting vsphere-problem-detector as a deployment

manifests/0000_90_cluster-storage-operator_01_prometheusrbac.yaml, manifests/03_credentials_request_vsphere.yaml
A PR was merged with new manifests that don't contain default annotation.
=> Bug 1907329: Add missing default cluster profile annotation

assets/csidriveroperators/aws-ebs/05_clusterrole.yaml, assets/csidriveroperators/gcp-pd/05_clusterrole.yaml, assets/csidriveroperators/manila/05_clusterrole.yaml, assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml, assets/csidriveroperators/ovirt/05_clusterrole.yaml, pkg/generated/bindata.go
This will be necessary so that CSI driver operators can read the proxy object.
=> Bug 1912945: Add RBAC rules to read proxy resource

manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml, manifests/0000_90_cluster-storage-operator_01_prometheusrbac.yaml, manifests/0000_90_cluster-storage-operator_02_servicemonitor.yaml, manifests/02_csi_driver_operators_namespace.yaml, manifests/03_credentials_request_aws.yaml, manifests/03_credentials_request_cinder.yaml, manifests/03_credentials_request_gcp.yaml, manifests/03_credentials_request_manila.yaml, manifests/03_credentials_request_ovirt.yaml, manifests/03_credentials_request_vsphere.yaml, manifests/06_operator_cr.yaml, manifests/07_service_account.yaml, manifests/08_operator_rbac.yaml, manifests/09_metrics_service.yaml, manifests/10_deployment.yaml, manifests/11_cluster_operator.yaml
This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-storage-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.
=> Bug 1915473: Annotate manifests for single-node-developer cluster profile

manifests/10_deployment.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1914451
cc @sttts @openshift/storage 
After the change:
```
~> oc exec cluster-storage-operator-77b4cffccb-bmtgb -i -t -- whoami
10400
```
=> Bug 1914451: Run CSO as non-root user

assets/vsphere_problem_detector/12_prometheusrules.yaml, go.mod, pkg/generated/bindata.go, pkg/operator/vsphereproblemdetector/monitoring.go, pkg/operator/vsphereproblemdetector/monitoring_test.go, vendor/modules.txt
Depends on https://github.com/openshift/vsphere-problem-detector/pull/24/files
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1904503
=> Bug 1904503: Add prometheus alerts for vsphere

assets/csidriveroperators/aws-ebs/05_clusterrole.yaml, assets/csidriveroperators/gcp-pd/05_clusterrole.yaml, assets/csidriveroperators/ovirt/05_clusterrole.yaml, pkg/generated/bindata.go
The Config Observer controller from CSI driver operators `1)` watches the `proxies` resource and `2)` patches/updates the `CR.Spec.ObservedConfig`.
PR https://github.com/openshift/cluster-storage-operator/pull/121 introduced the RBAC rule for `#1`, but it missed the rule for `#2`.
=> Bug 1912945: Add RBAC to allow operator to update CR's spec

pkg/operator/csidriveroperator/crcontroller.go
With this PR CSO will no longer update/patch the CR.
If the CR doesn't exist, CSO will create it. However, if the already CR exists, CSO won't update it with the config that it sees fit.
This is a requirement for the CSI Config Observer Controller used in CSI driver operators. That controller watches `proxies` resources and writes the observed config in `CR.Spec.observedConfig`. Without this PR, CSO would overwrite that field.
=> Bug 1910581: CSO shouldn't overwrite clustercsidriver objects

pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/starter.go
Adjusts the relatedObjects of the `storage` CO to only include the relevant CSI Drivers instead of every driver.
=> Bug 1883538: Only include the relevant drivers in relatedObjects

assets/vsphere_problem_detector/02_role.yaml, pkg/generated/bindata.go
Currently the vsphere problem detector logs this on every start:
> W0202 14:52:17.121173       1 builder.go:207] unable to get owner reference (falling back to namespace): replicasets.apps "vsphere-problem-detector-operator-65f56d5b76" is forbidden: User "system:serviceaccount:openshift-cluster-storage-operator:vsphere-problem-detector-operator" cannot get resource "replicasets" in API group "apps" in the namespace "openshift-cluster-storage-operator"
This PR adds replicasets to the vsphere role to address this issue.
=> Bug 1923098: Add replicasets to vsphere permissions

assets/storageclasses/vsphere.yaml, pkg/generated/bindata.go
library-go compares the existing + expected StorageClass without defaulting, therefore thinking that `volumeBindingMode: Immediate` and `volumeBindingMode: nil` are different and re-deploying the storage class with every sync (10 minutes).
Update the vSphere StorageClass with the binding mode to make the comparison work.
=> vsphere: don't redeploy StorageClass in every sync

assets/csidriveroperators/gcp-pd/07_deployment.yaml, assets/csidriveroperators/openstack-cinder/07_deployment.yaml, pkg/generated/bindata.go
Looks like oversight, GCE PD and Cinder CSI driver operators did not get logLevel parameter.
@bertinatto, PTAL
=> Propagate log level to GCE and Cinder CSI driver operators

manifests/03_credentials_request_aws.yaml
For a new way of managing OpenShift credentials on AWS to work, using Security
Token Service, we need external tooling to know the service account names from
the Credentials Request manifest so that it can create IAM Roles that can be
assumed only by those specific service accounts.
Managing credentials using STS ref: https://github.com/openshift/cloud-credential-operator/blob/master/docs/sts.md
Tooling design ref: https://issues.redhat.com/browse/CCO-60
/cc @joelddiaz
=> Add service account names to credentials request manifest

assets/csidriveroperators/aws-ebs/09_deployment.yaml, assets/csidriveroperators/azure-disk/08_deployment.yaml, assets/csidriveroperators/gcp-pd/07_deployment.yaml, assets/csidriveroperators/manila/07_deployment.yaml, assets/csidriveroperators/openstack-cinder/07_deployment.yaml, assets/csidriveroperators/ovirt/07_deployment.yaml, manifests/10_deployment.yaml, manifests/image-references, pkg/generated/bindata.go, pkg/operator/csidriveroperator/util.go
So they can use the right kube-rbac-proxy image in their Pods.
=> Pass KUBE_RBAC_PROXY_IMAGE to CSI driver operators

assets/csidriveroperators/azure-disk/06_clusterrole.yaml, assets/csidriveroperators/vsphere/06_clusterrole.yaml, pkg/generated/bindata.go
Azure Disk and vSphere CSI driver operators need permissions to create TokenReviews to authenticate Prometheus when it's collecting metrics.
=> Add TokenReview permissions to newly introduced operators

pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/csidriveroperator/driverstarter_test.go
When opt-in CSI driver should be installed and the driver is already installed, but it's not the OpenShift one, Degrade the whole cluster and wait until user removes the other (community) CSI driver.
This affects only CSI drivers that are installed after TechPreviewNoUpgrade FeatureSet is set.
We distinguish "our" CSI driver by presence of annotation "csi.openshift.io/managed".
Passing CSIDriver to `shouldRunController` to simplify unit tests.
=> Degrade the cluster when an unsupported CSI driver is already installed

assets/csidriveroperators/aws-ebs/09_deployment.yaml, assets/csidriveroperators/gcp-pd/07_deployment.yaml, assets/csidriveroperators/manila/07_deployment.yaml, assets/csidriveroperators/openstack-cinder/07_deployment.yaml, assets/csidriveroperators/ovirt/07_deployment.yaml, assets/csidriveroperators/vsphere/08_deployment.yaml, manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml, manifests/02_csi_driver_operators_namespace.yaml, manifests/10_deployment.yaml, pkg/generated/bindata.go
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Add management workload annotations

manifests/10_deployment.yaml, manifests/image-references
This is the third step described here: https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#removing-or-renaming-an-image-from-an-openshift-release-image
=> Remove "vmware" prefix from CSI operator and driver

manifests/image-references
Trying to fix this error: https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.8.0-0.nightly/release/4.8.0-0.nightly-2021-04-12-222417
=> Bug 1949041: Update image-references for vsphere

assets/csidriveroperators/vsphere/08_deployment.yaml, pkg/generated/bindata.go
To be able to run kube-rbac-proxy pods to collect metrics via HTTPS.
=> Bug 1949554: Pass KUBE_RBAC_PROXY to vSphere CSI driver operator

.gitignore, Makefile, go.mod, go.sum, manifests/10_deployment-ibm-cloud-managed.yaml, profile-patches/ibm-cloud-managed/10_deployment.yaml-patch, vendor/github.com/openshift/build-machinery-go/Makefile, vendor/github.com/openshift/build-machinery-go/README.md, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk, vendor/modules.txt
Bumps build-machinery-go to latest
Adds patch specific to ibm-cloud-managed profile that removes node selector for operator deployment
`make verify` verifies that the generated manifest is up to date
`make update` updates the manifest by applying the ibm-cloud-managed patch to the original deployment manifest
=> Bug 1948721: IBM Cloud manifest profile patch

assets/csidriveroperators/vsphere/06_clusterrole.yaml, pkg/generated/bindata.go
The operator needs to watch the `proxies` resource and update the `clustercsidriver`'s spec. This patch adds the missing RBAC rules that allow those actions.
Similar PRs for other operators:
https://github.com/openshift/cluster-storage-operator/pull/121
https://github.com/openshift/cluster-storage-operator/pull/127
=> Bug 1948505: Add missing RBAC rules for vSphere

assets/csidriveroperators/manila/05_clusterrole.yaml, pkg/generated/bindata.go
To be able to create Service and grand permission to Prometheus to list objects to collect metrics from them.
=> Bug 1949357: Add missing RBAC rules to Manila operator

assets/csidriveroperators/aws-ebs/09_deployment.yaml, assets/csidriveroperators/azure-disk/08_deployment.yaml, assets/csidriveroperators/gcp-pd/07_deployment.yaml, assets/csidriveroperators/manila/07_deployment.yaml, assets/csidriveroperators/openstack-cinder/07_deployment.yaml, assets/csidriveroperators/ovirt/07_deployment.yaml, assets/csidriveroperators/vsphere/08_deployment.yaml, manifests/10_deployment-ibm-cloud-managed.yaml, manifests/10_deployment.yaml, pkg/generated/bindata.go
As per openshift/enhancements#739, the workload annotations names are changing.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged
=> Rename workload annotations

go.mod, go.sum, vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go, vendor/k8s.io/apiserver/pkg/server/options/authentication.go, vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go, vendor/modules.txt
This repository uses the delegated authentication which has been identified to contain a bug that increases the number of watch requests against the Kube API server.
We provided a temporary branch that contains a fix and switched this repository to that branch.
With this change, k8s.io/apiserver points to temporary-watch-reduction-patch-1.21 to pick up k/k/pull/101102
Feel free to remove it once the upstream PR merges and a new Z release is cut.
=> Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout

assets/vsphere_problem_detector/12_prometheusrules.yaml, pkg/generated/bindata.go
Following https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md, using Warning severity + long `Description` + 60 minutes for the alert to fire. Not sure if alerts should be that talkative.
This PR depends on https://github.com/openshift/vsphere-problem-detector/pull/39 to provide the metric to alert on.
=> Bug 1943719: Add alert about vsphere-problem-detector unable to connect

manifests/08_operator_rbac.yaml
ClusterRoleBindings are non-namespaced objects, so they should not set namespace in the manifest. This makes CVO hotloop on this manifest, attempting to reconcile it
=> Bug 1961538: manifests: remove namespace from cluster-storage-operator-role binding

assets/csidriveroperators/openstack-cinder/07_deployment.yaml, pkg/generated/bindata.go
To fetch a list of AZs from Cinder, the operator needs credentials and certificates.
This PR mounts them to the deployment's pods.
=> Bug 1936871: Add volumes with credentials to Cinder operator deployment

assets/csidriveroperators/aws-ebs/03_role.yaml, assets/csidriveroperators/azure-disk/04_role.yaml, assets/csidriveroperators/gcp-pd/03_role.yaml, assets/csidriveroperators/manila/05_clusterrole.yaml, assets/csidriveroperators/openstack-cinder/03_role.yaml, assets/csidriveroperators/ovirt/03_role.yaml, assets/csidriveroperators/vsphere/04_role.yaml, assets/vsphere_problem_detector/02_role.yaml, pkg/generated/bindata.go
This PR added permissions to operators service monitoring, allowing cluster version upgrade.
Currently the operators has `create` permission. When upgrading the cluster, it needs permission to `update` the service role.
=> Bug 1961120: added permissions to service monitoring

assets/csidriveroperators/aws-ebs/03_role.yaml, pkg/generated/bindata.go
This is required by github.com/openshift/aws-ebs-csi-driver-operator/pull/122.
=> Bug 1947402: Add permissions poddisruptionbudgets in AWS CSI operator'

assets/csidriveroperators/ovirt/05_clusterrole.yaml
We need to add permissions to get, list and watch pods for PR https://github.com/openshift/ovirt-csi-driver-operator/pull/64/files#diff-be967bcd761c2fada6b517801fd5972ba5ae149ad579c6a31d9e2d158ac0d961R21-R23
=> Add permissions to get, list and watch pods for ovirt-csi-operator

pkg/operator/csidriveroperator/csioperatorclient/types.go, pkg/operator/csidriveroperator/deploymentcontroller.go, pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go
If running on a cluster with control plane topology of type 'External' (as in ROKS or Hypershift), CSI operators should not be scheduled to masters. This change sets the node selector to empty if this is the case.
=> Support external control plane topology

assets/vsphere_problem_detector/12_prometheusrules.yaml
When the CSI driver is installed (i.e. `TechPreviewNoUpgrade` is set), alert when there is a VMs with HW version < 15.
If I understand promql, `ON()` is required to have logical `and` with two unrelated queries.
=> Add alert about HW version < 15

manifests/10_deployment.yaml
For ibm-cloud-managed we are already creating an alternate deployment manifest without a master node selector. This removes the annotation from the main deployment manifest so the CVO only uses one or the other.
=> Remove ibm-cloud-managed annotation from operator deployment

assets/csidriveroperators/vsphere/06_clusterrole.yaml
=> Add new driver permissions for vmware-vsphere-csi-operator

assets/csidriveroperators/vsphere/02_configmap.yaml, assets/csidriveroperators/vsphere/08_deployment.yaml, assets/vsphere_problem_detector/06_configmap.yaml, assets/vsphere_problem_detector/07_deployment.yaml, pkg/operator/csidriveroperator/csioperatorclient/vsphere.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_starter.go
Use cluster's CA bundle when talking to vCenter.
/assign @gnufied
=> Bug 1969719: Add trusted CA bundle to vsphere operators

manifests/03_credentials_request_gcp.yaml
For enabling short-lived credentials in gcp cluster using workload
identity (similar to AWS STS), we need ccoctl tool to know the
kubernetes service account names from the credentials request
manifest so that it can create gcp service accounts that can be
impersonated only by specific kubernetes service accounts.
ref: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
=> Add service account names to gcp credentials request manifest

assets/vsphere_problem_detector/12_prometheusrules.yaml
- `for:` is always 10m
- prometheus expression is always `[5m]`
To keep the alerts consistent.
=> Bug 1982300: Unify alert times

assets/csidriveroperators/manila/03_role.yaml, assets/csidriveroperators/manila/05_clusterrole.yaml
The Manila CSI operator creates a PDB in the `openshift-manila-csi-driver` namespace, not in the `openshift-cluster-csi-drivers` one (like the other CSI operators).
I'm moving this to a ClusterRole, but we review anf fix the Role instead. I'll create a BZ for that.
=> Bug 1948090: Fix poddisruptionbudget RBAC rule for Manila

pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/csidriveroperator/driverstarter_test.go
Since Azure Stack Hub does not support in-tree volume plugin for azure disk, we have to always enable the CSI driver for this platform.
This commit checks if we use Azure Stack Hub and enables the driver, even if the feature gate may not be set.
=> Bug 1990601: Always run CSI driver controller for Azure Stack Hub

pkg/operator/csidriveroperator/csioperatorclient/types.go, pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/csidriveroperator/driverstarter_test.go
Allow platform-agnostic CSI drivers to be installed on all platforms.
This allows CSI drivers that do not depend on a specific cloud provider
to be installed by the cluster storage operator.
=>  Bug 1986557: Install CSI drivers on all platforms

assets/csidriveroperators/azure-disk/06_clusterrole.yaml
To allow syncing "cloud-provider-config" cm from "openshift-config" namespace with "openshift-cluster-csi-drivers", we have to provide the operator the appropriate permissions.
=> Bug 1992857: allow Azure CSI driver operator to read configmaps globally

pkg/operator/csidriveroperator/deploymentcontroller.go, pkg/operator/csidriveroperator/util.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go
Currently, we deploy only one replica of the CSI operator Deployment. This apparently leads to CSO going unavailable when draining the node where a CSI operator is running on.
A reasonable way to fix this issue would be to run multiple replicas of the CSI operator, however, we chose to remove the _CSIDriverOperatorDeploymentAvailable_ condition instead. This condition was was being set to _False_ when draining the node where the CSI operator was running on, cascading the status up to the top _Available_ condition (through the unioning done in the CR controller in CSO).
From now on, the unioning that determines the top _Available_ state relies on the other _Available_ conditions reported by other controllers and by the CSI operator.
In addition to that, I introduced a health check for the …
=> Bug 1948090: Remove CSIDriverOperatorDeploymentAvailable condition when deploying CSI operator

assets/csidriveroperators/openstack-cinder/07_deployment.yaml
Adds annotation to inject proxy env vars
to cinder-csi-driver-operator when proxy
is being used.
=> Bug 1985391: Add proxy support to cinder CSI

pkg/operator/csidriveroperator/csioperatorclient/types.go, pkg/operator/csidriveroperator/deploymentcontroller.go, pkg/operator/csidriveroperator/driverstarter.go
Partially reverts changes from #187 
Fixes clearing the node selector when control plane topology is set to External.
=> Bug 1999853: ControlPlaneTopology: Fix node selector for CSI driver operator deployment

assets/csidriveroperators/azure-disk/08_deployment.yaml, manifests/03_credentials_request_azure.yaml, manifests/10_deployment-ibm-cloud-managed.yaml, manifests/10_deployment.yaml, manifests/image-references, pkg/operator/csidriveroperator/csioperatorclient/azure-disk.go
Add credentials for Azure Disk CSI driver via cloud-credentials-operator.
In addition, pass name of cluster-cloud-controller-manager-operator image to Azure CSI driver operator, so the operator can merge cloud config + the new credentials easily (see #https://github.com/openshift/azure-disk-csi-driver-operator/pull/30).
=> Bug 1992875: Add azure credentials

assets/vsphere_problem_detector/12_prometheusrules.yaml, pkg/dependencymagnet/dependencymagnet.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1999674
=> Bug 1999674: Update prometheus rule to alert about esxi host versions

assets/csidriveroperators/openstack-cinder/07_deployment.yaml, pkg/generated/bindata.go
Adds annotation to inject proxy env vars
to cinder-csi-driver-operator when proxy
is being used.
=> Bug 1996672: Add proxy support to cinder CSI

pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
vSphere CSI Driver & Operator are going to be GA in 4.10, so they need to be installed by default.
=> Install vSphere CSI Driver and Operator by default

pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
This reverts commit 0134c1c0d3442465a74c3c4a880202451ffd4861.
The vsphere CSI driver is producing large numbers of client requests.
Our vCenter instances cannot support the vsphere csi driver running on
many concurrent CI clusters without starving some vsphere clusters.
We need to revert this PR until the number of connections can be reduced
so that we can keep running multiple concurrent CI clusters.
stop-gap for https://bugzilla.redhat.com/show_bug.cgi?id=2009859 to get back to a functional CI state.
=> Revert "Install vSphere CSI Driver by default"

assets/csidriveroperators/manila/01_namespace.yaml, manifests/02_csi_driver_operators_namespace.yaml
Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-cluster-csi-drivers` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz
=> podsecurity: enforce privileged for openshift-cluster-csi-drivers namespace

pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
We believe we fixed the leaking of sessions in the vSphere CSI Driver Operator [1], so we will install the vSphere CSI Driver Operator on all vSphere clusters again and see how it goes.
CC @rvanderp3 @deads2k @openshift/storage
[1] https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/47
=> Bug 2009859: Install vSphere CSI Driver by default (again)

pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/csidriveroperator/driverstarter_test.go
Azure Disk CSI driver is installed by default, both on Azure cloud and Azure stack. We don't need to distinguish these two platform any longer.
As side effect, this will stop installing Azure File CSI driver operator on Azure Stack Hub. It should be installed via TechPreviewNoUpgrade there too.
This reverts PR #200.
=> Bug 2015635: Remove Azure Stack Hub detection.

assets/csidriveroperators/shared-resource/05_clusterrole.yaml
Reign in the Shared Resource Operator permissions
for Custom Resource Definitions.
We need a blanket CREATE permission for ALL CRDs
But only need list,get,watch,delete for sharedconfigmaps and
sharedsecrets.
=> Update Shared Resource Operator permissions

pkg/csoclients/csoclients.go, pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/csidriveroperator/driverstarter_test.go
When starting a CSI driver operator and discovering its dependencies / `RelatedObjects`, some APIs may be temporarily missing in the API server. RESTMapper is caching the error responses, so make sure to refresh the cache in the next sync.
I tried to fix the caching in [client-go](https://github.com/kubernetes/kubernetes/pull/104814), but it seems it's not going anywhere.
=> Bug 2001761: Fix RelatedObjects when RBAC API is missing

assets/csidriveroperators/alibaba-disk/02_sa.yaml, assets/csidriveroperators/alibaba-disk/03_role.yaml, assets/csidriveroperators/alibaba-disk/04_rolebinding.yaml, assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml, assets/csidriveroperators/alibaba-disk/06_clusterrolebinding.yaml, assets/csidriveroperators/alibaba-disk/07_deployment.yaml, assets/csidriveroperators/alibaba-disk/08_cr.yaml, manifests/10_deployment-ibm-cloud-managed.yaml, manifests/10_deployment.yaml, manifests/image-references, pkg/operator/csidriveroperator/csioperatorclient/alibaba-disk.go, pkg/operator/starter.go
Tested with force-installing the driver on AWS, it needs https://github.com/openshift/alibaba-disk-csi-driver-operator/pull/12, but otherwise it started the CSI driver DaemonSet + Deployment. Driver pods crashed because they were running on a wrong cloud.
=> Add Alibaba Disk CSI driver

assets/csidriveroperators/shared-resource/09_deployment.yaml
Currently CSI shared resource operator pod does not know about the TLS certificate it has to use and the port for the metrics. That should be changed in the deployment.
=> Bug 2030364: Setup port, mount TLS cert into CSI shared resource operator

assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
This line was not intended to be included in https://github.com/openshift/cluster-storage-operator/pull/242
It's causing the deployment to fail:
```
root@3065a3db5912:/go/src/github.com/openshift/installer# oc --kubeconfig cluster-deploys/ipi-dev-storage-10/auth/kubeconfig logs -n openshift-cluster-csi-drivers ibm-vpc-block-csi-driver-operator-55d7b64d85-wpcs4 
Error: unknown shorthand flag: 'v' in -v=2
Usage:
ibm-vpc-block-csi-driver-operator start [flags]
Flags:
--config string                    Location of the master configuration file to run from.
-h, --help                             help for start
--kubeconfig string                Location of the master configuration file to run from.
--listen string                    The ip:port to serve on.
--namespace string …
```
=> Remove invalid -v argument from IBM VPC operator deployment

assets/csidriveroperators/vsphere/02_configmap.yaml, assets/csidriveroperators/vsphere/08_deployment.yaml, assets/vsphere_problem_detector/06_configmap.yaml, assets/vsphere_problem_detector/07_deployment.yaml, go.mod, go.sum, pkg/dependencymagnet/dependencymagnet.go, pkg/generated/bindata.go, pkg/operator/csidriveroperator/csioperatorclient/vsphere.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_starter.go, vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/golang.mk, vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk, vendor/modules.txt
Use cluster's CA bundle when talking to vCenter.
Backport of #178 to 4.8
=> [4.8] Bug 2034270: Add trusted CA bundle to vsphere operators

assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2033111
/hold
until https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/11 merges
That PR is required first to add the `-v` argument back to the operator
=> Bug 2033111: IBM VPC operator library bump removed global CLI args

assets/vsphere_problem_detector/06_configmap.yaml, assets/vsphere_problem_detector/07_deployment.yaml, pkg/dependencymagnet/dependencymagnet.go, pkg/generated/bindata.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_starter.go
Use cluster's CA bundle when talking to vCenter.
Backport of https://github.com/openshift/cluster-storage-operator/pull/178 to 4.7
=> [4.7] Bug 2030740: Add trusted CA bundle to vsphere operators

pkg/operator/starter.go
Add non-namespaced ClusterRoleBinding that's created by CVO to RelatedObjects. All other non-namepaced objects are already there, including both namespaces that are related to the operator.
=> Bug 1961317: Add operator's ClusterRoleBinding to RelatedObjects

assets/csidriveroperators/aws-ebs/05_clusterrole.yaml, assets/csidriveroperators/azure-disk/06_clusterrole.yaml, assets/csidriveroperators/azure-file/06_clusterrole.yaml, assets/csidriveroperators/gcp-pd/05_clusterrole.yaml, assets/csidriveroperators/ibm-vpc-block/06_clusterrole.yaml, assets/csidriveroperators/manila/05_clusterrole.yaml, assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml, assets/csidriveroperators/ovirt/05_clusterrole.yaml, assets/csidriveroperators/shared-resource/05_clusterrole.yaml, assets/csidriveroperators/vsphere/06_clusterrole.yaml
This adds the new required RBAC rules for external-snapshotter v5.0.1:
- volumesnapshotcontents:patch
- volumesnapshotcontents/status:patch (already existed)
- volumesnapshots:patch
- volumesnapshots/status:patch
See https://github.com/openshift/csi-external-snapshotter/pull/66
=> Bug 2043130: Update CSI sidecars to the latest release for 4.10

assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml
They're required by the new external-snapshotter sidecar.
=> Bug 2047025: Add "patch" permissions to Alibaba CSI driver operator

manifests/03_credentials_request_alibaba.yaml, manifests/03_credentials_request_aws.yaml, manifests/03_credentials_request_azure.yaml, manifests/03_credentials_request_azure_file.yaml, manifests/03_credentials_request_ibm.yaml, manifests/03_credentials_request_manila.yaml, manifests/03_credentials_request_ovirt.yaml, manifests/03_credentials_request_vsphere_csi.yaml, manifests/03_credentials_request_vsphere_detector.yaml, manifests/ibm-cloud-managed-cleanup.yaml
The ibm-cloud-managed profile doesn't use the cloud-credential-operator.
The CredentialsRequest CRs should not be installed in that environment.
Unmark the existing CredentialsRequests so they are no longer installed
in ibm-cloud-managed.
Create a list of previously-installed CredentialsRequests so that they
are cleaned up by the CVO only on the ibm-cloud-managed profile.
xref: https://issues.redhat.com/browse/CCO-177
=> no CredentialsRequests in ibm-cloud-managed

manifests/0000_90_cluster-storage-operator_01_prometheusrbac.yaml
Currently, the servicemonitor but not the rbac is deployed which breaks
the scraping.
=> Add missing ibm cloud annotations to prometheus rbac

manifests/10_deployment-ibm-cloud-managed.yaml, manifests/10_deployment.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
"objectRef": "openshift-cluster-storage-operator/deployments/cluster-storage-operator",
"pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"cluster-storage-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted c
apabilities (container \"cluster-storage-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"cluster-storage-operator\" must set …
```
=> manifests/deployment: comply to restricted pod security level

assets/vsphere_problem_detector/12_prometheusrules.yaml
Updated existing ESXi host check to emit info alert when running with a host older that 7.0.2 + added the same alert for vCenter version too.
=> Bug 2077599: Alert on vCenter < 7.0.2

assets/storageclasses/gcp.yaml
Reverts openshift/cluster-storage-operator#273. Clean revert.
GCP upgrade jobs are failing since this was merged with:
```
{Failed to upgrade storage, operator was not available (DefaultStorageClassController_SyncError): DefaultStorageClassControllerAvailable: StorageClass.storage.k8s.io "standard" is invalid: parameters: Forbidden: updates to parameters are forbidden.  Failed to upgrade storage, operator was not available (DefaultStorageClassController_SyncError): DefaultStorageClassControllerAvailable: StorageClass.storage.k8s.io "standard" is invalid: parameters: Forbidden: updates to parameters are forbidden.}
```
Example run https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-e2e-gcp-upgrade/1525003893585481728
=> Bug 2077050: Revert "OCP should default to pd-ssd disk type on GCP"

assets/csidriveroperators/shared-resource/09_deployment.yaml
After the go.mod bumps in https://github.com/openshift/csi-driver-shared-resource-operator/pull/48 we now hit klog v2 pain on startup:
```
2022-05-23T23:10:05.349862146Z Error: unknown shorthand flag: 'v' in -v=2
2022-05-23T23:10:05.350357211Z Usage:
2022-05-23T23:10:05.350357211Z   shared-resources-operator start [flags]
2022-05-23T23:10:05.350357211Z 
2022-05-23T23:10:05.350357211Z Flags:
2022-05-23T23:10:05.350357211Z       --config string                    Location of the master configuration file to run from.
2022-05-23T23:10:05.350357211Z   -h, --help                             help for start
2022-05-23T23:10:05.350357211Z       --kubeconfig string                Location of the master configuration file to run from.
2022-05-23T23:10:05.350357211Z       --listen string …
```
=> Bug 2088533: remove unused '-v' for shared resource operator as part of klogv2/openshift api/ k8s bump

pkg/operator/defaultstorageclass/controller.go, pkg/operator/defaultstorageclass/controller_test.go
Letting newStorageClassForCluster() default to unsupportedPlatformError is not appropriate because later in sync this results in reporting `"No default StorageClass for this platform"`. Instead we should report this message for Azure and OpenStack:
`"StorageClass provided by supplied CSI Driver instead of the cluster-storage-operator"`
=> Bug 2101645: DefaultStorageClassController reports fake message on azure and openstack

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/modules.txt
Bump library-go so that we include [this](https://github.com/openshift/library-go/pull/1355) change from library-go in gcp driver operator. This should allow changing/re-creating the StorageClass allowing downgrade from 4.11 to 4.10 which now fails because the re-creation is not allowed.
=> Bug 2098655: gcp cluster rollback fails due to storage failure

pkg/operator/defaultstorageclass/controller.go, pkg/operator/defaultstorageclass/controller_test.go
Backport PR [#292](https://github.com/openshift/cluster-storage-operator/pull/292) to 4.11.
=>  Bug 2102576: DefaultStorageClassController reports fake message on azure and openstack 

pkg/operator/defaultstorageclass/controller.go
Fix message for IBM and Alibaba cloud so a ClusterOperator condition reports:
`"StorageClass provided by supplied CSI Driver instead of the cluster-storage-operator"`
instead of:
`"No default StorageClass for this platform"`
For Nutanix and any other platforms we don't support the message should still be:
`"No default StorageClass for this platform"`
https://bugzilla.redhat.com/show_bug.cgi?id=2112237
=> Bug 2112237: correct sc error messages for ibm and alibaba platforms

assets/csidriveroperators/powervs-block/04_clusterrole.yaml
Resource csi.storage.k8s.io/csinodeinfos added to powervs-block-csi-d river-operator-clusterrole.
Fixes the warnings in storage cluster operator - PowerVS CSI driver deployment.
Redhat bugzilla: https://issues.redhat.com/browse/OCPBUGS-946
=> OCPBUGS-946: Resource csi.storage.k8s.io/csinodeinfos added to powervs-block-csi-d river-operator-clusterrole

.ci-operator.yaml, Dockerfile, pkg/operator/csidriveroperator/olmremovalcontroller.go, pkg/operator/defaultstorageclass/controller.go, pkg/operator/snapshotcrd/controller.go
Based on https://github.com/openshift/cluster-storage-operator/pull/320, bump go to 1.19 and fix gofmt.
=> Bump go to 1.19

manifests/10_deployment-ibm-cloud-managed.yaml, manifests/10_deployment.yaml
OCP will assign its own UID to the Pod. This helps in HyperShift, where UIDs of different guest control planes should be different.
=> Remove specific UID from cluster-storage-operator

manifests/12_prometheusrules.yaml
Show an alert when all attach or mount operations for a volume plugin (or CSI driver) are failing on a node for 5 minutes. A single success will make the alert go away.
=> Bug 2093016: Add alert about attach / mount failing

pkg/operator/csidriveroperator/driverstarter.go, pkg/operator/csidriveroperator/driverstarter_test.go
Don't panic when user sets `fg.Spec.FeatureSet`, but leaves `fg.Spec.CustomNoUpgrade` nil or empty. It is a weird configuration, where user wants custom flags but does not set any, but the operator should not crash.
=> OCPBUGS-2880: Fix panic on empty featureGate.spec.customNoUpgrade

manifests/12_prometheusrules.yaml
=> OCPBUGS-4508:User real node name in failing mount alerts

assets/csidriveroperators/aws-ebs/hypershift/mgmt/09_deployment.yaml
`aws-ebs-csi-driver-operator` runs in the mgmt cluster and does not need to be configured with the guest cluster proxy
hypershift proxy conformance test currently fails because the `storage` CO never becomes `Available`
https://k8s-testgrid.appspot.com/redhat-hypershift#4.13-conformance-aws-ovn-proxy
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn-proxy/1623517300822904832/artifacts/conformance-aws-ovn-proxy/dump/artifacts/namespaces/clusters-70d2a995b41e8ac652b7/core/pods/logs/aws-ebs-csi-driver-operator-84df7c667b-7mlxq-aws-ebs-csi-driver-operator-previous.log
=> OCPBUGS-7300: hypershift: remove inject-proxy annotation from aws-ebs-csi-driver-operator deployment

manifests/10_deployment-hypershift.yaml, manifests/10_deployment-ibm-cloud-managed.yaml, manifests/10_deployment.yaml
When there is a custom SCC with `runAsUser: type: runAsNonRoot`, CSO pod can match it. Then the Pod must have a non-root UID assigned to be able to run.
This moves the CSO Pods from `restricted-v2` SCC to `nonroot-v2` SCC in the default OCP installation.
This is a workaround for CSO using cluster-admin role, which can allow CSO to use any SCC. If CSO had specific role(s) to use only few selected SCCs, we could remove this patch.
=> OCPBUGS-6992: Add UID to CSO Pod to be able to run with custom SCCs

manifests/03_credentials_request_aws.yaml
When a snapshot is shared in AWS the KMS key needs to be shared as well with a set of permissions documented here:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-modifying-snapshot-permissions.html#share-kms-key
Without the 'kms:ReEncrypt*' permissions restoring a PVC from an encrypted snapshot fails.
=> OCPBUGS-5410: add ReEncrypt KMS permissions

assets/csidriveroperators/aws-ebs/hypershift/mgmt/02_sa.yaml
https://issues.redhat.com/browse/OCPBUGS-8328
=> OCPBUGS-8328: assets: csi: hypershift: add pull-secret to aws-ebs-csi-driver-operator ServiceAccount

assets/csidriveroperators/manila/01_namespace.yaml
Tag the `openshift-manila-csi-driver` namespace with the proper
`workload.openshift.io/allowed` label in order to support the Management
Workload Partitioning enhancement proposal [1].
[1] https://github.com/openshift/enhancements/blob/master/enhancements/workload-partitioning/management-workload-partitioning.md
=> OCPBUGS-11112: Add missing workload label to openshift-manila-csi-driver NS

assets/vsphere_problem_detector/07_deployment.yaml
To support the workload partitioning we need to add the required annotations (https://github.com/openshift/enhancements/pull/703).
=>  OCPBUGS-8683: Add management workloads annotations

assets/csidriveroperators/aws-ebs/hypershift/mgmt/01_operator_role.yaml, assets/csidriveroperators/aws-ebs/hypershift/mgmt/09_deployment.yaml, pkg/csoclients/csoclients.go, pkg/csoclients/fake.go, pkg/operator/csidriveroperator/deploymentcontroller.go, pkg/operator/csidriveroperator/hypershift_deployment_controller.go, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go, pkg/utils/deployment_controller.go, vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go, vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go, vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go, vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go, vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go, vendor/k8s.io/client-go/dynamic/fake/simple.go, vendor/modules.txt
Set affinity, tolerations, node selector and priority rules for operands in the hosted control plane.
This is a manual cherry-pick of https://github.com/openshift/cluster-storage-operator/pull/352
=> [4.12] OCPBUGS-10646: Hypershift: set control plane operand properties

go.mod, go.sum, vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml, vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml, vendor/github.com/openshift/api/operator/v1/types_storage.go, vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go, vendor/modules.txt
https://issues.redhat.com/browse/OCPBUGS-11729
This PR bumps openshift/api to get the latest API change to the Storage CR in 4.14.
=> OCPBUGS-11729: VSphereStorageDriver does not document the platform default

go.mod, pkg/operator/vsphereproblemdetector/config.go, pkg/operator/vsphereproblemdetector/config_test.go, pkg/operator/vsphereproblemdetector/monitoring.go
Create/delete detector's PrometheusRule instances based on value of ConfigMap `vsphere-problem-detector`.
Example:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: vsphere-problem-detector
namespace: openshift-cluster-storage-operator
data:
config.yaml: |
alertsDisabled: true
```
=> OCPBUGS-13187: Make vsphere-problem-detector alerts configurable

manifests/03_credentials_request_azure.yaml, manifests/03_credentials_request_azure_file.yaml
Add the necessary serviceAccountNames to the azure-disk-csi-driver-operator and azure-file-csi-driver-operator credentials requests to enable Azure workload identity tokens.
=> CCO-319: Add serviceAccountNames to azure-disk and azure-file credentials

manifests/03_credentials_request_aws.yaml
As mentioned in upstream fast-restore docs: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/fast-snapshot-restores.md#prerequisites
=> STOR-1167: Add permissions needed by fast snapshots to AWS CSI driver

manifests/openshift-csi-provisioner-configmap-and-secret-reader-role.yaml, manifests/openshift-csi-provisioner-volumeattachment-reader-role.yaml, manifests/openshift-csi-provisioner-volumesnapshot-reader-role.yaml, manifests/openshift-csi-resizer-infrastructure-reader-role.yaml, manifests/openshift-csi-resizer-storageclass-reader-role.yaml, manifests/sidecar-main_attacher_role.yaml, manifests/sidecar-main_provisioner_role.yaml, manifests/sidecar-main_resizer_role.yaml, manifests/sidecar-main_snapshotter_role.yaml
The PR adds a bunch of new ClusterRoles to `manifests/` dir. This way those new ClusterRoles will be always created, regardless of cloud. They are building blocks to compose ClusterRoles for CSI dirver sidecars. For example, `external-provisioner` sidecar for `aws-ebs` csi driver can compose the same ClusterRole as in https://github.com/openshift/aws-ebs-csi-driver-operator/blob/master/assets/rbac/provisioner_role.yaml by adding ClusterRoleBindings for `openshift-csi-main-provisioner-role` and `openshift-csi-provisioner-volumesnapshot-reader-role`. The only exception is `leases` rules which need to be moved from ClusterRoles to per-namespace Roles anyway.
As soon as this change is merged into `cluster-storage-operator`, it will be possible to get rid of ClusterRole definitions in csi …
=> STOR-1065: Publish ClusterRoles for csi driver sidecars

manifests/12_prometheusrules.yaml
Since 4.13 volume provisioning won't fail any more when multiple defaults SCs are present because one is always picked: https://github.com/kubernetes/kubernetes/pull/110559/commits/f12325add3fbac8a2ce31cb12b4649c01d74f248
It no longer makes sense for this alert to be critical - lowering it's severity to warning.
=> OCPBUGS-14053: decrease severity for MultipleDefaultStorageClasses alert

assets/vsphere_problem_detector/12_prometheusrules.yaml
=> OCPBUGS-13696: Warn about CBT enabled VMs via vsphere-problem-detector

go.mod, go.sum, pkg/operator/operator_starter.go, vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go, vendor/modules.txt
Remove all unknown version from storage's ClusterOperator.Status.
This will clean `AWSEBSCSIDriverOperator` entry introduced in 4.8.
=> OCPBUGS-11359: Remove unused versions from status

manifests/09_sidecar-main_provisioner_role.yaml
Let's keep `manifests/09_sidecar-main_provisioner_role.yaml` in sync with upstream (https://github.com/openshift/csi-external-provisioner/blob/master/deploy/kubernetes/rbac.yaml)
See discussion at https://github.com/openshift/aws-ebs-csi-driver-operator/pull/245.
=> Remove "get" verb from "events" resource of RBAC for provisioner sidecar

manifests/12_prometheusrules.yaml
Use `ignoring(status)` to match *only* rows that have *all* the same labels except for `status`.
`on()` would match a failing volume plugin with *any* other volume plugin / node that has not succeeded in past 5 minutes, e.g. with HostPath that had no activity (= zero successes) in the past 5 minutes.
=> OCPBUGS-17356: Fix PodStartupStorageOperationsFailing alert

manifests/10_deployment-hypershift.yaml, profile-patches/hypershift/10_deployment.yaml-patch
Need to update this first as the authoritative source for https://github.com/openshift/hypershift/blob/main/control-plane-operator/controllers/hostedcontrolplane/storage/assets/10_deployment-hypershift.yaml
=> STOR-1432: hypershift: add independent refs for AWS EBS driver controller images

assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml, assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml, pkg/operator/csidriveroperator/csioperatorclient/aws.go, pkg/operator/csidriveroperator/util.go
continuing work of
* https://github.com/openshift/cluster-storage-operator/pull/392
* https://github.com/openshift/hypershift/pull/2882
with a follow on in https://github.com/openshift/aws-ebs-csi-driver-operator
https://github.com/openshift/aws-ebs-csi-driver-operator/pull/252
=> STOR-1432: hypershift: pass through control plane images to AWS EBS CSI driver operator

manifests/03_credentials_request_azure.yaml, manifests/03_credentials_request_azure_file.yaml
Set granular permissions according to upstream documentation:
Azure Disk: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md
Azure File: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md
Also one extra permission needed was discovered by CI tests and added for Azure Disk: `'Microsoft.Compute/virtualMachines/write'`
And a few more discovered by QE tests: 
`'Microsoft.Network/networkSecurityGroups/join/action'`
`'Microsoft.Network/virtualNetworks/subnets/read'`
`'Microsoft.Network/virtualNetworks/subnets/write'`
=> STOR-1274: use granular permissons for Azure credential requests

assets/csidriveroperators/shared-resource/standalone/09_deployment.yaml, assets/csidriveroperators/vsphere/08_deployment.yaml, manifests/10_deployment-hypershift.yaml, manifests/10_deployment-ibm-cloud-managed.yaml, manifests/10_deployment.yaml, pkg/operator/vsphereproblemdetector/vsphere_problem_detector_starter.go
Adding `WithSecretHashAnnotationHook()` for `vsphere-problem-detector-serving-cert` ensures that new annotation is published in `vsphere-problem-detector-operator` deployment. This, in turn, leads to operator pods restart.
The second patch in this PR adds commnad-line option `--terminate-on-files` to operators denedent on `metrics-serving-cert`:
* CSO operator itself (uses secret `cluster-storage-operator-serving-cert`)
* vmware-vsphere operator (uses secret `vmware-vsphere-csi-driver-operator-metrics-serving-cert`)
* shared-resource operator (uses secret `shared-resource-csi-driver-operator-metrics-serving-cert`)
Hence, if corresponding secrets change, the operators are restarted.
=> STOR-1446: Restart `vsphere-problem-detector-operator` Pods if `serving-cert` changed

assets/csidriveroperators/vsphere/06_clusterrole.yaml
Goes with https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/169
Fixes OCPBUGS-18132
=> OCPBUGS-18132: Add patch for allowing configmap updates via clusterrole

assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml, assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
Fixes https://issues.redhat.com/browse/OCPBUGS-19073
=> OCPBUGS-19073: Move KAS access label to right place

assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml, assets/csidriveroperators/aws-ebs/base/05_clusterrole.yaml, assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml, assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml, assets/csidriveroperators/azure-disk/06_clusterrole.yaml, assets/csidriveroperators/azure-file/06_clusterrole.yaml, assets/csidriveroperators/gcp-pd/05_clusterrole.yaml, assets/csidriveroperators/ibm-vpc-block/06_clusterrole.yaml, assets/csidriveroperators/manila/05_clusterrole.yaml, assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml, assets/csidriveroperators/ovirt/05_clusterrole.yaml, assets/csidriveroperators/powervs-block/hypershift/guest/04_clusterrole.yaml, assets/csidriveroperators/powervs-block/standalone/04_clusterrole.yaml, assets/csidriveroperators/vsphere/06_clusterrole.yaml
The operators need to get `spec.tlsSecurityProfile` from apiserver cluster to construct command-line options `--tls-cipher-suites` and `--tls-min-version` for kube RBAC proxy sidecars.
=> STOR-1453: Grant permissions to access `apiserver` to CSI driver operators

pkg/operator/csidriveroperator/driver_starter.go
https://issues.redhat.com/browse/OCPBUGS-23120
The upgradeable condition used to be set by SnapshotCRDController, but that was removed in https://github.com/openshift/cluster-storage-operator/pull/385/commits/fa9af3aad65b9d0e9c618453825e4defeaad59ac
DefaultStorageClassController only sets upgradeable=True if [unsupportedPlatformError](https://github.com/openshift/cluster-storage-operator/blob/dbb1514dbf9923c56a4a198374cc59e45f9bc0cc/pkg/operator/defaultstorageclass/controller.go#L97-L100).
IBM VPC returns [supportedbyCSIError](https://github.com/openshift/cluster-storage-operator/blob/dbb1514dbf9923c56a4a198374cc59e45f9bc0cc/pkg/operator/defaultstorageclass/controller.go#L207) instead.
The current code assumes if supportedbyCSIError, then [csidriveroperator …
=> OCPBUGS-23120: [IBM ROKS] cluster-storage-operator does not set upgradeable=True

assets/csidriveroperators/shared-resource/standalone/05_clusterrole.yaml
https://issues.redhat.com/browse/OCPBUGS-24027
=> OCPBUGS-24027: forbidden access to resource on shared-resource-csi-driver-operator

manifests/03_credentials_request_gcp.yaml
Reverts #410 ; tracked by [TRT-1376](https://issues.redhat.com//browse/TRT-1376)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
This PR appears to have retriggered the limits we're hitting with GCP roles similar to earlier this week. We are reverting to buy the CCO team time to figure out what to do.
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
Suspect you'll need to work with CCO team to get clearance for …
```
=> TRT-1376: Revert #410 "CCO-251: use granular permissions for gcp credentails request"

manifests/12_prometheusrules.yaml
Create new SELinux metrics to send through telemetry to remove all labels except for `volume_plugin`. See https://issues.redhat.com/browse/STOR-1277.
=> STOR-1277: Add Prometheus rules for SELinux telemetry

manifests/03_credentials_request_alibaba.yaml, manifests/03_credentials_request_aws.yaml, manifests/03_credentials_request_azure.yaml, manifests/03_credentials_request_azure_file.yaml, manifests/03_credentials_request_cinder.yaml, manifests/03_credentials_request_gcp.yaml, manifests/03_credentials_request_ibm.yaml, manifests/03_credentials_request_manila.yaml, manifests/03_credentials_request_ovirt.yaml, manifests/03_credentials_request_powervs.yaml, manifests/03_credentials_request_vsphere_csi.yaml, manifests/03_credentials_request_vsphere_detector.yaml, manifests/ibm-cloud-managed-cleanup.yaml
Add capability annotations to cloud credentials requests
=> OCPVE-789: annotate credentials request manifests

manifests/03_credentials_request_gcp.yaml
Undo this revert without any changes: https://github.com/openshift/cluster-storage-operator/pull/426
Origin PR: https://github.com/openshift/cluster-storage-operator/pull/410
This replaces https://github.com/openshift/cluster-storage-operator/pull/427, without having fine-grained permissions.
=> CCO-251: replace instanceAdmin role with specific compute permissions

manifests/12_prometheusrules.yaml
The alert fired only when there was a successful operation on a node. If a CSI driver / volume plugin always failed on a node, the alert was silent, because `increase(storage_operation_duration_seconds_count{status = "success")[5m])` has no data.
Trying to fix it with more elaborate promql. When `increase(...{status = "success"}` has no data, supplement its value by `increase(...{status != "success"}) * 0`. We know that non-successful metric exists, so multiply it by zero to get a metric of successes with zero values.
Then use `sum without(status)` and `ignoring(status)` to merge the metrics by all other labels than status.
=> OCPBUGS-22422: Fix PodStartupStorageOperationsFailing alert

pkg/operator/operator_starter.go
When RunOperator() returns no error, library-go waits for leader election goroutine to release the leadership before exiting.
An error returned from RunOperator() takes a shortcut and leads to much faster exit(1), not giving the election goroutine time to release its lease. A subsequent operator pod needs to wait for the old lease to expire, which slows down cluster upgrade and any development / debugging that needs the operator restarted.
=> STOR-1714: Release leadership on SIGTERM

assets/vsphere_problem_detector/12_prometheusrules.yaml
Move rules that are used to sanitize OCP metric for telemetry from cluster-monitoring-operator here. These rules are used only for storage metrics and should live with storage code.
cluster-monitoring-operator PR that removes the rules from their code: https://github.com/openshift/cluster-monitoring-operator/pull/2235
=> STOR-1289: Move vSphere prometheus rules to CSO

pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
vmware-vsphere-csi-driver-operator disables the driver when it cannot talk to vCenter, e.g. when it does not have valid credentials. This enables processing of condition `xxxDisabled: true` introduced in https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/218.
=> OCPBUGS-27159: Allow vSphere CSI driver to be disabled

assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml, manifests/10_deployment-hypershift.yaml, manifests/10_deployment-ibm-cloud-managed.yaml, manifests/10_deployment.yaml, manifests/image-references, pkg/operator/csidriveroperator/csioperatorclient/ibm-vpc-block.go, profile-patches/hypershift/10_deployment.yaml-patch
https://issues.redhat.com/browse/STOR-1611
Since https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/89 merged, ibm-vpc-node-label-updater is no longer used or deployed. We can remove it from CSO and eventually from the payload.
=> STOR-1611: remove ibm-vpc-node-label-updater

assets/csidriveroperators/azure-disk/base/08_deployment.yaml, assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
The standalone patch already adds the master selector to the deployment. It should not be in the base yaml.
=> OCPBUGS-28765: Remove master node selector from azure-csi-driver-operator deployment

pkg/operator/starter.go
It is more helpful to show which storage classes were detected as default. There's an alert when more than one default is present and this message might help debug such cases in the future.
Message example:
```
I0221 16:55:09.385977   65866 starter.go:63] Current default StorageClass count: 2 ([thin-csi thin-csi2])
```
=> OCPBUGS-28748: log default storage class names when collector is triggered

pkg/operator/vsphereproblemdetector/vsphere_problem_detector_starter.go
This is a partial revert of https://github.com/openshift/cluster-storage-operator/pull/456
Unless we have to change the name of the controller for some reason we could revert it back instead of cleaning it up.
=> OCPBUGS-34590: revert vsphere problem detector controller name change

assets/csidriveroperators/vsphere/08_deployment.yaml
https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/233 will do `allowOperatorRemovedState=True` for vsphere csi operator. This will trigger finalazer check in library-go:
```
if management.IsOperatorRemovable() {
if err := v1helpers.EnsureFinalizer(ctx, c.operatorClient, c.name); err != nil {
```
`EnsureFinalizer()`, in turn, calculates finalizer name either as `os.Getenv("OPERATOR_NAME")` or `os.Args[0]`. The latter doesn't work for vsphere because leading slash in `/usr/bin/vmware-vsphere-csi-driver-operator` is not allowed:
```
E0701 19:43:32.342151       1 base_controller.go:268] VMwareVSphereDriverControllerServiceController reconciliation failed: ClusterCSIDriver.operator.openshift.io "csi.vsphere.vmware.com" is invalid: metadata.finalizers: Invalid value: …
```
=> STOR-1767: add env var OPERATOR_NAME to vsphere csi operator deployment

manifests/12_prometheusrules.yaml
The MultipleDefaultStorageClasses alert was present 5 minutes after this problem was fixed and there was only 1 default storage class. This PR fixes this issue.
=> OCPBUGS-36169: deactivate MultipleDefaultStorageClasses alert immediately after being fixed

manifests/12_prometheusrules.yaml
These rules have until now lived in
https://github.com/openshift/cluster-monitoring-operator, where they where generated from
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/de834e9a291b49396125768f041e2078763f48b5/alerts/storage_alerts.libsonnet. This however rarely changes so I'm committing the manifest here along with some comments.
=> MON-2065: manifests: add k8s storage rules

pkg/operator/csidriveroperator/deploymentcontroller.go, pkg/operator/csidriveroperator/hypershift_deployment_controller.go, pkg/utils/deployment_controller.go
The HostedCluster object for hypershift recently got a [new feature](https://github.com/openshift/hypershift/pull/4339) that allows users creating HCP clusters to set custom tolerations on their HCP pods. The CSO needs to integrate this feature in the same way it integrated the NodeSelector feature for HCP.
=> CNV-44992: HCP custom tolerations integration

manifests/03_credentials_request_gcp.yaml
Add `TagUser` role to the credentials request created for the GCP PD storage operator, required adding tags to the GCP resources created by the driver.
=> CFE-879: Add TagUser role to creadentials request of GCP PD operator

manifests/03_credentials_request_azure_file.yaml
Now that the installer has switched from Terraform to using cluster api to provision Azure clusters, the node subnet is created with an (empty) route table attached. In order to provision a volume on the subnet, permissions to join the route table are required.
=> OCPBUGS-37663: include azure perms for route table

Dockerfile, Dockerfile.rhel7
CRD schemas are now created here: https://github.com/openshift/api/pull/2032.
This allso prevents changes like [this](https://github.com/openshift/cluster-storage-operator/commit/076e178df7aa8bd9753a2b5de9aa14542412a757) when adding new TechPreview fields to ClusterCSIDriver CRDs.
=> NO-JIRA: create CRDs from openshift/api

hack/generate-manifests.sh
- ``hack: Address shellcheck issues``
- ``hack: Make HyperShift asset generation optional``
- ``hack: Always recreate manifests``
=> NO-JIRA: Always recreate manifests

assets/csidriveroperators/shared-resource/hypershift/mgmt/02_sa.yaml
The ServiceAccount for the shared-resource-csi-driver-operator that runs on the mgmt cluster does not have the HCP pull secret configured
```
$ oc get sa shared-resource-csi-driver-operator -oyaml
apiVersion: v1
imagePullSecrets:
- name: shared-resource-csi-driver-operator-dockercfg-qwzsg
kind: ServiceAccount
...
```
This causes image pull failure
```
16m         Warning   Failed                        pod/shared-resource-csi-driver-operator-7d9798f764-ft9jg    Failed to pull image "registry.ci.openshift.org/ocp/4.18-2024-10-10-065553@sha256:1be01d122d1e9375f318548763608b461d62c72b78457962ed14f5b60526738d": unable to retrieve auth token: invalid username/password: authentication required
```
cc @jsafrane @gnufied
=> NO-JIRA: assets: shared-resource: hypershift: add pull-secret to operator SA

pkg/operator/csidriveroperator/hypershift_deployment_controller.go
This commit adds environment variables needed by a CSI deployment for ARO HCP.
=> HOSTEDCP-2033: Add ARO HCP environment vars to CSI deployment

pkg/operator/csidriveroperator/hypershift_deployment_controller.go
- Correct ARO HCP environment vars for CSI driver operator deployment(We deepCopy the driver operator deploy in proxy hook https://github.com/openshift/cluster-storage-operator/compare/master...Phaow:hotfix?expand=1#diff-40fd8e85c74d747fd9f412fcf74ff56c582d612aaf2775c422d6f97729f3a173R129-R130 and finally apply the deepCopy object, so we needs use the deepCopy object to inject the new env vars for dirver operatos otherwise the new env vars won't be added).
- Only inject the used env var for different dirver operators. (Previous codes will inject both `ARO_HCP_SECRET_PROVIDER_CLASS_FOR_DISK` and `ARO_HCP_SECRET_PROVIDER_CLASS_FOR_FILE` env vars for both disk and file dirver operators while each operator only needs its own one)
**Local test record on azure aks hcp**
```console
$ oc get …
```
=> HOSTEDCP-2033: Correct ARO HCP environment vars for CSI driver operator deployment

manifests/12_prometheusrules.yaml
The alert gives false-positives for the following scenario (100% repoducible): failure, success, ~2mins pause, failure, success, ~2mins pause, etc.
The essence of issue (false-positives) is a typo in promql query: the closing bracket for `sum without(status) (` came too early, before `or`. This is a problem because the `sum` operator is greedy, it is stronger then `or`. So it was applied to the first operand in brackets:
```
sum without(status) (increase(storage_operation_duration_seconds_count{status = "success", operation_name =~"volume_attach|volume_mount"}[60m]))
```
The patch fixes issue by moving closing bracket farhter, beyond `or ...`:
```
sum without(status) (increase(storage_operation_duration_seconds_count{status = "success", operation_name =~"volume_attach|volume_mount"}[60m]) …
```
=> OCPBUGS-43767: Fix PodStartupStorageOperationsFailing alert

assets/csidriveroperators/azure-disk/hypershift/mgmt/deployment.patch.yaml, assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml, assets/csidriveroperators/azure-file/hypershift/mgmt/deployment.patch.yaml, assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml, manifests/10_deployment-hypershift.yaml, pkg/operator/csidriveroperator/util.go, profile-patches/hypershift/10_deployment.yaml-patch
This is a manual cherry-pick of:
- https://github.com/openshift/cluster-storage-operator/pull/515
- https://github.com/openshift/cluster-storage-operator/pull/518
- https://github.com/openshift/cluster-storage-operator/pull/522
=> OCPBUGS-43794: add ability to control kube rbac proxy container image on controlplane

OWNERS, OWNERS_ALIASES
To allow us to review/approve OpenStack-related changes to `openshift/release`, since the `OWNERS` files there are auto-generated from this one.
https://github.com/openshift/csi-operator/pull/315 does this for `openshift/csi-operator`.
=> NO-JIRA: Add openstack-approvers to root OWNERS

assets/csidriveroperators/aws-ebs/hypershift/guest/generated/operator.openshift.io_v1_clustercsidriver_ebs.csi.aws.com.yaml, assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml, assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_aws-ebs-csi-driver-operator-clusterrolebinding.yaml, assets/csidriveroperators/aws-ebs/hypershift/guest/kustomization.yaml, assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml, assets/csidriveroperators/aws-ebs/hypershift/mgmt/kustomization.yaml, assets/csidriveroperators/aws-ebs/standalone/generated/operator.openshift.io_v1_clustercsidriver_ebs.csi.aws.com.yaml, assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml, assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_aws-ebs-csi-driver-operator-clusterrolebinding.yaml, assets/csidriveroperators/aws-ebs/standalone/kustomization.yaml, assets/csidriveroperators/azure-disk/hypershift/guest/generated/operator.openshift.io_v1_clustercsidriver_disk.csi.azure.com.yaml, assets/csidriveroperators/azure-disk/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-disk-csi-driver-operator-clusterrole.yaml, assets/csidriveroperators/azure-disk/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-disk-csi-driver-operator-clusterrolebinding.yaml, assets/csidriveroperators/azure-disk/hypershift/guest/kustomization.yaml, assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml, assets/csidriveroperators/azure-disk/hypershift/mgmt/kustomization.yaml, assets/csidriveroperators/azure-disk/standalone/generated/operator.openshift.io_v1_clustercsidriver_disk.csi.azure.com.yaml, assets/csidriveroperators/azure-disk/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-disk-csi-driver-operator-clusterrole.yaml, assets/csidriveroperators/azure-disk/standalone/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-disk-csi-driver-operator-clusterrolebinding.yaml, assets/csidriveroperators/azure-disk/standalone/kustomization.yaml, assets/csidriveroperators/azure-file/hypershift/guest/generated/operator.openshift.io_v1_clustercsidriver_file.csi.azure.com.yaml, assets/csidriveroperators/azure-file/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-file-csi-driver-operator-clusterrole.yaml, assets/csidriveroperators/azure-file/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-file-csi-driver-operator-clusterrolebinding.yaml, assets/csidriveroperators/azure-file/hypershift/guest/kustomization.yaml, assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml, assets/csidriveroperators/azure-file/hypershift/mgmt/kustomization.yaml, assets/csidriveroperators/azure-file/standalone/generated/operator.openshift.io_v1_clustercsidriver_file.csi.azure.com.yaml, assets/csidriveroperators/azure-file/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-file-csi-driver-operator-clusterrole.yaml, assets/csidriveroperators/azure-file/standalone/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-file-csi-driver-operator-clusterrolebinding.yaml, assets/csidriveroperators/azure-file/standalone/kustomization.yaml
These provide no value once we have run kustomize and could be confusing. Remove them.
Yes, this is a nit but I think it's helpful.
=> NO-JIRA: Remove kustomize-related annotations from generated assets

pkg/operator/csidriveroperator/csioperatorclient/aws.go
Adding `OPERATOR_IMAGE_VERSION` variable to AWS EBS operator.
=> STOR-2078: Add OPERATOR_IMAGE_VERSION var to AWS-EBS operator

pkg/operator/csidriveroperator/deploymentcontroller.go, pkg/operator/csidriveroperator/hypershift_deployment_controller.go, pkg/utils/deployment_controller.go
HCP is adding a new API field to allow users creating HCP clusters to set custom labels on all HCP pods https://github.com/openshift/hypershift/pull/5114. cluster-storage-operator needs to integrate this feature in the same way it integrated the NodeSelector feature for HCP.
=> OCPBUGS-45073: Support HCP labels

pkg/operator/operator_starter.go, vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go, vendor/modules.txt
During upgrade from 4.15 to 4.16 an error can happen when VSphereProblemDetectorDeploymentControllerAvailable condition is present from 4.15, but 4.16 and later versions don't use it anymore and users can get stuck during upgrade. This PR fixed the problem.
To test, add the condition using `oc edit --subresource=status --output-patch storage cluster`, after that CSO should remove it.
=> OCPBUGS-50668: fix Vsphere cluster Storage operator in Unavailable state

manifests/03_credentials_request_azure_file.yaml
If users configure a storage class with `networkEndpointType: privateEndpoint` parameter CSI driver will fail to provision a volume due to missing permissions.
I've cross checked the OCPBUGS-54491 bug report with upstream documentation to see what we miss and also noticed a few more that were also missing upstream when testing the private endpoints manually. After discussing this with upstream the list was extended with the missing ones: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2513
This CredentialsRequest object is used when installing or upgrading cluster, by extracting it from payload and passing it to `ccoctl` which creates Azure roles with the permissions listed. This might result in granting more privileges than most users need.
Alternatively we could drop this …
=> OCPBUGS-54491: sync Azure File permissions with upstream docs

manifests/03_credentials_request_cinder.yaml
-  The cinder csi driver operator CredentialsRequest name uses `openshift-cluster-csi-drivers` seems a bit mislead, correct it to `openstack-cinder-csi-driver-operator` which is more clear which operator uses it.
=> NO-JIRA: correct cinder operator CredentialsRequest name

assets/csidriveroperators/gcp-pd/07_deployment.yaml
https://issues.redhat.com//browse/STOR-2330
This PR subscribes GCP PD CSI driver operator pods to NPs from https://github.com/openshift/cluster-storage-operator/pull/579
=> STOR-2330: Add labels to subscribe GCP PD CSI driver operator to NPs

manifests/03_credentials_request_azure.yaml, manifests/03_credentials_request_azure_file.yaml
Sync Azure CSI driver permissions with upstream versions that we have in OCP 4.19:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md?plain=1
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/v1.33.0/docs/driver-parameters.md?plain=1
AzureDisk file diff upstream and this PR :
```diff
- Microsoft.Compute/diskEncryptionSets/read
- Microsoft.Compute/disks/beginGetAccess/action
- Microsoft.Compute/disks/delete
- Microsoft.Compute/disks/read
- Microsoft.Compute/disks/write
- Microsoft.Compute/locations/DiskOperations/read
- Microsoft.Compute/locations/operations/read
- Microsoft.Compute/snapshots/delete
- Microsoft.Compute/snapshots/read
- Microsoft.Compute/snapshots/write
- Microsoft.Compute/virtualMachineScaleSets/read
- …
```
=> OCPBUGS-44128: OCPBUGS-44127: Sync azure permissions

assets/csidriveroperators/ibm-vpc-block/04_role.yaml
The operator needs to manage NP "allow-ingress-to-ibm-vpc-block-metrics". See https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/148 for details.
=> STOR-2330: Add RBAC rule to let ibm-vpc-block-csi-driver-operator manage NetworkPolicy

assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml, assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml, assets/csidriveroperators/azure-disk/hypershift/mgmt/deployment.patch.yaml, assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml, assets/csidriveroperators/azure-file/hypershift/mgmt/deployment.patch.yaml, assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml, assets/csidriveroperators/openstack-cinder/hypershift/mgmt/deployment.patch.yaml, assets/csidriveroperators/openstack-cinder/hypershift/mgmt/generated/apps_v1_deployment_openstack-cinder-csi-driver-operator.yaml, assets/csidriveroperators/powervs-block/hypershift/mgmt/06_deployment.yaml
HCM is looking to export logs indexed on the `app` label but some components in the HCP are missing the label.
This PR adds the `app` label to the CSI driver operators deployed on the HCP.
=> OCPBUGS-60064: hypershift: add app label to csdriveroperators running in HCP

manifests/12_prometheusrules.yaml
`:total` suffix is reserved to counter and this is not a counter. `:count` was suggested in [telemetry configuration review](https://github.com/openshift/cluster-monitoring-operator/pull/2653).
=> OCPBUGS-60948: Rename the SELinuxMount metric to :count
