pkg/controller/clusterstorage/clusterstorage_controller.go

Made a series of dumb mistakes/assumptions, I moved yamls without changing the code, this should fix the operator insta-panicking

Fix panic because yaml assets path is wrong

---

manifests/02-deployment.yaml

fixes https://github.com/openshift/cluster-storage-operator/issues/1

Assign cluster-storage-operator priority system-cluster-critical and run on master nodes

---

Dockerfile
manifests/02-deployment.yaml
manifests/03-cluster-operator.yaml
pkg/controller/clusterstorage/clusterstorage_controller.go

Following conventions defined by all other operators.

The cluster storage operator should report the name "storage"

---

assets/vsphere.yaml
pkg/controller/clusterstorage/clusterstorage_controller.go
pkg/generated/bindata.go

We will need to manually test this with a cluster where the cloudprovider is configured.

Add vsphere default storageclass

---

manifests/02-deployment.yaml

fix https://bugzilla.redhat.com/show_bug.cgi?id=1707059

Set terminationMessagePolicy to “FallbackToLogsOnError”

---

manifests/02-deployment.yaml

in service to https://github.com/openshift/origin/pull/22787

manifests: add resource requests to operator pod

---

pkg/controller/clusterstorage/clusterstorage_controller.go

https://bugzilla.redhat.com/show_bug.cgi?id=1717640

Add related objects to status

---

pkg/controller/clusterstorage/clusterstorage_controller.go

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1727044

Bug 1727044: Set missing Upgradeable condition

---

assets/openstack.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=1741419

Bug 1741419: Fixed OpenStack class annotation name

---

assets/csidriveroperators/manila/05_clusterrole.yaml
pkg/generated/bindata.go

It needs to read/write ConfigMaps too.
See https://github.com/openshift/csi-driver-manila-operator/pull/49.

Bug 1867735: Sync RBAC rules from Manila operator

---

pkg/operator/defaultstorageclass/controller.go

Currently if a platform has a CSI Driver but not a default SC (such as oVirt), we display the following error message:
> DefaultStorageClassControllerAvailable: No default StorageClass for this platform
This makes it a bit clearer that the SC is provided by a corresponding CSI driver. I've included the other supported platforms where we ship the CSI driver to future-proof the PR.

Bug 1872549: Updated error message when SC is installed via CSI

---

pkg/controller/clusterstorage/clusterstorage_controller.go

Moves the v1alpha1 Snapshot CRD check to later in Reconcile, so that we can proceed with z-stream upgrades.

Bug 1874873: Move notUpgradeable check later to prevent z-stream upgrade failures

---

manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml
manifests/02_csi_driver_operators_namespace.yaml
manifests/03_credentials_request_aws.yaml
manifests/03_credentials_request_openstack.yaml
manifests/03_credentials_request_ovirt.yaml
manifests/06_operator_cr.yaml
manifests/07_service_account.yaml
manifests/08_operator_rbac.yaml
manifests/09_deployment.yaml
manifests/10_cluster_operator.yaml

This is matches openshift/enhancements#510 and doesn't change existing behavior

add current profile annotations to CVO manifests

---

assets/vsphere_problem_detector/04_clusterrole.yaml
pkg/generated/bindata.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1914119

Bug 1914119: Add RBAC for status field

---

assets/vsphere_problem_detector/12_prometheusrules.yaml
pkg/generated/bindata.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1917551

Bug 1917551: Change metric used in alerts for vsphere problem detector

---

assets/csidriveroperators/aws-ebs/01_namespace.yaml
assets/csidriveroperators/manila/01_namespace.yaml
assets/csidriveroperators/ovirt/01_namespace.yaml
manifests/02_csi_driver_operators_namespace.yaml
pkg/generated/bindata.go

[release-4.6] Bug 1921599: Add annotations to cluster-csi-drivers namespace

---

assets/vsphere_problem_detector/06_deployment.yaml
pkg/generated/bindata.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1938236

Allow log level to be replaced

---

assets/csidriveroperators/azure-disk/03_sa.yaml
assets/csidriveroperators/azure-disk/04_role.yaml
assets/csidriveroperators/azure-disk/05_rolebinding.yaml
assets/csidriveroperators/azure-disk/06_clusterrole.yaml
assets/csidriveroperators/azure-disk/07_clusterrolebinding.yaml
assets/csidriveroperators/azure-disk/08_deployment.yaml
assets/csidriveroperators/azure-disk/09_cr.yaml
manifests/10_deployment.yaml
manifests/image-references
pkg/generated/bindata.go
pkg/operator/csidriveroperator/csioperatorclient/azure-disk.go
pkg/operator/starter.go

Add AzureDisk CSI driver installation

---

assets/csidriveroperators/vsphere/08_deployment.yaml
manifests/10_deployment.yaml
manifests/image-references
pkg/generated/bindata.go
pkg/operator/csidriveroperator/csioperatorclient/vsphere.go

Ensure that vmware syncer is updated with latest image
I am going to put this on hold for a bit, because images aren't there yet.

Add vsphere syncer deployment

---

assets/csidriveroperators/vsphere/08_deployment.yaml
pkg/generated/bindata.go

Bug 1948448: Add log level to vSphere operator

---

assets/csidriveroperators/azure-disk/08_deployment.yaml
pkg/generated/bindata.go

Adds log level to the Azure Disk CSI Driver Operator

Bug 1947866: Add log level to Azure Disk CSI Operator

---

assets/csidriveroperators/manila/03_role.yaml
assets/csidriveroperators/manila/05_clusterrole.yaml
pkg/generated/bindata.go

Bug 1949357: Allow Manila operator to create ServiceMonitor in the driver namespace

---

assets/csidriveroperators/vsphere/08_deployment.yaml
pkg/generated/bindata.go

Bug 1947360: vSphere: set CPU/memory resource request

---

assets/csidriveroperators/vsphere/06_clusterrole.yaml

Add permissions to vSphere operator to create ValidatingWebhookConfiguration objects

---

assets/csidriveroperators/azure-disk/04_role.yaml
assets/csidriveroperators/gcp-pd/03_role.yaml
assets/csidriveroperators/manila/03_role.yaml
assets/csidriveroperators/openstack-cinder/03_role.yaml
assets/csidriveroperators/ovirt/03_role.yaml
assets/csidriveroperators/vsphere/04_role.yaml

 Bug 1972028: Add RBAC rules for CSI operators to handle poddisruptionbudgets

---

pkg/operator/starter.go

Currently we're relying on a loop iterator variable to start controllers. This may cause controllers being overriden during their execution.

Bug 1992193: Fix race when starting controllers

---

pkg/operator/csidriveroperator/csioperatorclient/azure-disk.go

Azure Disk CSI Driver is GA in 4.10

Install Azure Disk CSI Driver by default

---

assets/csidriveroperators/azure-file/08_deployment.yaml

Add missing env var for Azure File

---

manifests/03_credentials_request_ibm.yaml

CR yaml added to copy secret to openshift-cluster-csi-drivers namespace

Credential Request added

---

manifests/03_credentials_request_alibaba.yaml

cc @openshift/storage 
Based on an example in https://github.com/openshift/cloud-credential-operator/pull/412 and initial list of permissions I got from Alibaba on slack .

Add CredentialsRequest for Alibaba Disk CSI driver

---

manifests/10_deployment-ibm-cloud-managed.yaml
manifests/10_deployment.yaml
manifests/image-references

The images are already mirrored to quay.io.

Replace registry.ci images with quay

---

manifests/image-references

Broken in https://github.com/openshift/cluster-storage-operator/pull/240

Bug 2027363: Fix reference to Azure File images

---

pkg/operator/csidriveroperator/crcontroller.go

xref:  https://bugzilla.redhat.com/show_bug.cgi?id=2038389

Bug 2038389: Union upgradeable conditions as well from ClusterCSIDriver objects

---

pkg/operator/csidriveroperator/crcontroller.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=2040880

Bug 2040880: Do not replace unknown condition with true when we union conditions

---

assets/vsphere_problem_detector/04_clusterrole.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2045112

Bug 2045112: Add leases rbac for vsphere-problem-detector

---

manifests/03_credentials_request_aws.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=2049872
/hold for testing

Bug 2049872: cluster storage operator AWS credentialsrequest lacks KMS privileges

---

pkg/operator/csidriveroperator/csioperatorclient/azure-file.go

Epic: https://issues.redhat.com/browse/STOR-736

Azure File CSI Driver Operator is GA in OCP 4.11

---

assets/storageclasses/gcp.yaml

Merge along with [PR](https://github.com/openshift/gcp-pd-csi-driver-operator/pull/47)

Bug 2077050: OCP should default to pd-ssd disk type on GCP

---

assets/csidriveroperators/shared-resource/09_deployment.yaml
manifests/10_deployment-ibm-cloud-managed.yaml
manifests/10_deployment.yaml
manifests/image-references
pkg/operator/csidriveroperator/csioperatorclient/shared-resource.go

Bug 2086231: BUILD-405: Install the Shared Resource CSI Driver WebHook

---

pkg/operator/defaultstorageclass/controller.go
pkg/operator/defaultstorageclass/controller_test.go

Don't flip `DefaultStorageClassController` `Available=true` -> `false` when it fails to talk to the API server. Storage is OK, most probably the API server is being updated.
When the controller fails constantly, it will get `Degraded=true` with some inertia.

Bug 2081557: Fix DefaultStorageClassController getting Available=False on error

---

assets/csidriveroperators/shared-resource/05_clusterrole.yaml

…dation.webhook.csidriversharedresource validatingwebhookconfiguration

Bug 2097400: Allow Shared Resource Driver to operate validating webhook

---

assets/csidriveroperators/alibaba-disk/07_deployment.yaml
assets/csidriveroperators/aws-ebs/09_deployment.yaml
assets/csidriveroperators/azure-disk/08_deployment.yaml
assets/csidriveroperators/azure-file/08_deployment.yaml
assets/csidriveroperators/gcp-pd/07_deployment.yaml
assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
assets/csidriveroperators/shared-resource/09_deployment.yaml
assets/csidriveroperators/vsphere/08_deployment.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=2107043

Bug 2107043: HTTPS_PROXY ENV missing in some CSI driver operators

---

assets/csidriveroperators/vsphere/13_prometheusrules.yaml
go.mod
go.sum
pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
pkg/operator/csidriveroperator/driverstarter.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/generic.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/images.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
vendor/modules.txt

Add info alert that upstream vSphere CSI driver is installed.

Bug 2108054: Add alert about unsupported CSI driver

---

assets/csidriveroperators/powervs-block/01_sa.yaml
assets/csidriveroperators/powervs-block/02_role.yaml
assets/csidriveroperators/powervs-block/03_rolebinding.yaml
assets/csidriveroperators/powervs-block/04_clusterrole.yaml
assets/csidriveroperators/powervs-block/05_clusterrolebinding.yaml
assets/csidriveroperators/powervs-block/06_deployment.yaml
assets/csidriveroperators/powervs-block/07_cr.yaml
manifests/03_credentials_request_powervs.yaml
manifests/10_deployment-ibm-cloud-managed.yaml
manifests/10_deployment.yaml
manifests/ibm-cloud-managed-cleanup.yaml
manifests/image-references
pkg/operator/csidriveroperator/csioperatorclient/powervs-block.go
pkg/operator/starter.go

Adding powervs block csi driver operator to the cluster storage operator to install powervs-block-csi-driver along with ocp installation on PowerVS platform.

Add PowerVS Block CSI Driver Operator

---

assets/csidriveroperators/shared-resource/12_servicemonitor.yaml
assets/csidriveroperators/vsphere/12_servicemonitor.yaml
assets/vsphere_problem_detector/11_service_monitor.yaml
manifests/0000_90_cluster-storage-operator_02_servicemonitor.yaml

Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md

TRT-534: Add client certificate and key to service monitor

---

assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml
assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
assets/csidriveroperators/azure-disk/06_clusterrole.yaml
assets/csidriveroperators/azure-file/06_clusterrole.yaml
assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
assets/csidriveroperators/ibm-vpc-block/06_clusterrole.yaml
assets/csidriveroperators/manila/05_clusterrole.yaml
assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
assets/csidriveroperators/ovirt/05_clusterrole.yaml
assets/csidriveroperators/powervs-block/04_clusterrole.yaml
assets/csidriveroperators/shared-resource/05_clusterrole.yaml

OCPBUGS-1904: Allow CSI operator to get CRDs

---

assets/vsphere_problem_detector/12_prometheusrules.yaml

Include `oc` command to get info about detected errors. And reformatted the file a bit.

OCPBUGS-1361: Reword vSphere problem detector check alerts

---

pkg/operator/defaultstorageclass/controller.go

Cherry-pick of https://github.com/openshift/cluster-storage-operator/pull/310

OCPBUGS-691: [release-4.10] correct sc error messages for ibm and alibaba platforms

---

assets/storageclasses/vsphere.yaml
pkg/operator/defaultstorageclass/controller.go
pkg/operator/defaultstorageclass/controller_test.go
pkg/operator/hypershift_starter.go
pkg/operator/standalone_starter.go
pkg/operator/starter.go

This reverts commit d11eda4143db4d801511fe9fe92e261536fabf5e, reversing changes made to 23834fbc5a45c37f438daaf4003f028fdf4f9ef9
Fixes https://issues.redhat.com/browse/OCPBUGS-7483

OCPBUGS-7483: Revert "Merge pull request #332 from bertinatto/default-sc"

---

assets/csidriveroperators/vsphere/15_prometheusrules.yaml

Show alert that topology is configured both in Infrastructure and ClusterCSIDriver.

STOR-1123: Add alert about topology misconfiguration

---

assets/csidriveroperators/aws-ebs/hypershift/mgmt/01_operator_role.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/09_deployment.yaml
pkg/csoclients/csoclients.go
pkg/csoclients/fake.go
pkg/operator/csidriveroperator/deploymentcontroller.go
pkg/operator/csidriveroperator/hypershift_deployment_controller.go
pkg/utils/deployment_controller.go
vendor/k8s.io/client-go/dynamic/fake/simple.go
vendor/modules.txt

Set affinity, tolerations, node selector and priority rules for operands in the hosted control plane.

OCPBUGS-8691: Hypershift: set control plane operand properties

---

assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml

Fixes https://issues.redhat.com/browse/OCPBUGS-19073

OCPBUGS-19073: Add KAS label to aws-ebs-operator

---

pkg/operator/csidriveroperator/driver_starter.go

https://issues.redhat.com/browse/OCPBUGS-23210
Manual backport of https://github.com/openshift/cluster-storage-operator/pull/417
/cc @openshift/storage @jeffnowicki

[release-4.14] OCPBUGS-23210: [IBM ROKS] cluster-storage-operator does not set upgradeable=True

---

assets/vsphere_problem_detector/12_prometheusrules.yaml

OCPBUGS-22994: Add UsernameWithoutDomain as a reason for triggering VSphereOpenshitConnectionFailure alert

---

assets/csidriveroperators/azure-file-original/08_deployment.yaml
assets/csidriveroperators/azure-file/base/08_deployment.yaml
assets/csidriveroperators/azure-file/hypershift/mgmt/deployment.patch.yaml
assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
assets/csidriveroperators/azure-file/standalone/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
assets/csidriveroperators/openstack-cinder/07_deployment.yaml
assets/csidriveroperators/powervs-block/hypershift/mgmt/06_deployment.yaml
assets/csidriveroperators/powervs-block/standalone/06_deployment.yaml
assets/csidriveroperators/shared-resource/hypershift/mgmt/09_deployment.yaml
assets/csidriveroperators/shared-resource/standalone/09_deployment.yaml
assets/csidriveroperators/vsphere/08_deployment.yaml

Addressing https://github.com/openshift/origin/pull/28777/files#r1592893974
/cc @deads2k @jsafrane

OCPBUGS-28230: enforce termination message policy on all platform pods

---

assets/csidriveroperators/aws-ebs/base/09_deployment.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
assets/csidriveroperators/aws-ebs/standalone/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
manifests/10_deployment-hypershift.yaml
manifests/10_deployment-ibm-cloud-managed.yaml
manifests/10_deployment.yaml

[OCPBUGS-36374](https://issues.redhat.com/browse/OCPBUGS-36374)
Manual cherry-pick of #459

[release-4.15] OCPBUGS-36374: Set required-scc for openshift workloads

---

pkg/operator/vsphereproblemdetector/monitoring.go

Delete detector's PrometheusRule instances if ClusterCSIDriver's ManagementState is equal to "Removed".

STOR-1767: Disable vsphere-problem-detector alerts if ManagementState==Removed

---

assets/csidriveroperators/aws-ebs/base/09_deployment.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
assets/csidriveroperators/aws-ebs/standalone/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
manifests/10_deployment-hypershift.yaml
manifests/10_deployment-ibm-cloud-managed.yaml
manifests/10_deployment.yaml
manifests/image-references
pkg/operator/csidriveroperator/util.go

OCPBUGS-37488: Pass TOOLS_IMAGE env var to AWS EBS CSI Driver operator

---

assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml

To allow https://github.com/openshift/release/pull/57308 to pass.

NO-JIRA: release-4.16: Run make update

---

assets/csidriveroperators/aws-ebs/base/09_deployment.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
assets/csidriveroperators/aws-ebs/standalone/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml

Add OPERATOR_IMAGE_VERSION to aws-ebs

STOR-2078: Add var OPERATOR_IMAGE_VERSION

---

manifests/09_openshift-csi-provisioner-volumeattributesclass-reader-role.yaml
manifests/09_openshift-csi-resizer-volumeattributesclass-reader-role.yaml

Noted: Resources are in plural form.

STOR-2078: Typo in clusterRole resources for VolumeAttributesClasses

---

assets/csidriveroperators/aws-ebs/base/05_clusterrole.yaml
assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml

VolumeAttributesClasses typo in resources

STOR-2078: VolumeAttributesClasses typo in resources

---

assets/csidriveroperators/aws-ebs/hypershift/mgmt/controller_add_hypershift_controller_minter.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/hypershift_token_minter.yaml
assets/csidriveroperators/aws-ebs/hypershift/mgmt/kustomization.yaml

Added Sidecar minter for aws-ebs-csi-driver-operator hypershift-deployments

CFE-1131: Added token minter Sidecar for aws-ebs hypershift-deployments

---

pkg/operator/operator_starter.go
vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
vendor/modules.txt

Manual cherry-pick of https://github.com/openshift/cluster-storage-operator/pull/558

[release-4.17] OCPBUGS-52222: fix Vsphere cluster Storage operator in Unavailable state

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
vendor/github.com/openshift/library-go/pkg/operator/deploymentcontroller/deployment_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiregistration.go
vendor/modules.txt

To pull deployment controller fix:
https://github.com/openshift/library-go/pull/1940

OCPBUGS-24588: bump library-go

---

assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
assets/csidriveroperators/gcp-pd/07_deployment.yaml
pkg/operator/csidriveroperator/csioperatorclient/gcp-pd.go

Enabling VolumeAttributesClass for GCP-PD driver and adding needed resources.

STOR-2078: Enable VolumeAttributesClass for GCP-PD

---

manifests/09_network-policy-allow-all-egress.yaml
manifests/09_network-policy-allow-egress-to-api-server.yaml
manifests/09_network-policy-allow-ingress-to-metrics.yaml
manifests/09_network-policy-allow-ingress-to-operator-metrics-range.yaml
manifests/09_network-policy-allow-to-dns.yaml

This PR includes basic NPs suitable for the most of CSI drivers and operators.

STOR-2330: Network Policies for CSI drivers and operators

---

assets/csidriveroperators/openstack-cinder/hypershift/mgmt/deployment.patch.yaml
assets/csidriveroperators/openstack-cinder/hypershift/mgmt/generated/apps_v1_deployment_openstack-cinder-csi-driver-operator.yaml
assets/csidriveroperators/openstack-cinder/standalone/deployment.patch.yaml
assets/csidriveroperators/openstack-cinder/standalone/generated/apps_v1_deployment_openstack-cinder-csi-driver-operator.yaml
assets/csidriveroperators/openstack-manila/hypershift/mgmt/deployment.patch.yaml
assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/apps_v1_deployment_manila-csi-driver-operator.yaml
assets/csidriveroperators/openstack-manila/standalone/deployment.patch.yaml
assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_apps_v1_deployment_manila-csi-driver-operator.yaml

https://issues.redhat.com//browse/STOR-2330
This PR subscribes openstack cinder and manila CSI driver operator pods to NPs from https://github.com/openshift/cluster-storage-operator/pull/579

STOR-2330: Add labels to subscribe openstack cinder and manila CSI driver operators to NPs

---

assets/csidriveroperators/powervs-block/hypershift/mgmt/06_deployment.yaml
assets/csidriveroperators/powervs-block/standalone/06_deployment.yaml

https://issues.redhat.com//browse/STOR-2330
This PR subscribe ibm-powervs-block CSI driver operator pods to NPs from https://github.com/openshift/cluster-storage-operator/pull/579
/cc @yussufsh @mkumatag

STOR-2330:  Add labels to subscribe ibm-powervs-block CSI driver operator to NPs

---

manifests/13_validating_admission_policy.yaml
manifests/14_validating_admission_policy_binding.yaml

Fixes 
https://issues.redhat.com/browse/STOR-2549

STOR-2549: Remove TP label from VAP files
